### PR TITLE
Fix Dr_i_1_calc equation

### PR DESCRIPTION
**Pull request by kickapoo**

### CODE REVIEW

**Comment by aptiko** [comment]
Could you create a unit test that fails without these changes but succeeds with the changes?

**Comment by kickapoo** [comment]
Yes but after re-installing 'six'  library.

**Comment by aptiko** [comment]
What do you mean? Should I wait for the unit test before accepting the pull request?

**Comment by kickapoo** [comment]
Sorry about the previous comment ( sent reply to wrong mail). Yes, I will
create a unit test as soon as possible.

**Comment by kickapoo** [comment]
Pull request is updated with the new (minor but crucial)  updates. 
Please note the major reduce of `unit test` cases. The provided test data, `pthelma/tests/data/IRMA_DW_Balance3`, has limited cases (general, no_irrigation, with_irrigation) and as a sequence `unit tests` follow the test data cases.

**Pull request closed without merging**
